app = "backend-laravel-api"

[build]
dockerfile = "backend/Dockerfile"
context = "."

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[services.ports]
port = 80
handlers = ["http"]

[[services.tcp_checks]]
interval = 10000
timeout = 5000
grace_period = "15s"
